### ISSUE TITLE
Layout change event on other-display dock exposure

### ISSUE THREAD

**Issue by warsaw** [Hammerspoon/hammerspoon.github.io#17]
I don't know if this is a bug or not, though if it's expected, I'd love to hear suggestions for workarounds.

Let's say you have multiple displays and you have a `hs.screen.watcher.new()` that reacts to layout changes, e.g.:

```
hs.screen.watcher.new(layout_change):start()
```

Now, `layout_changes` is a function that checks a bunch of conditions and depending on those, moves and resizes your windows.  Generally your layout isn't going to change very often, but there's one annoying case where it can happen at unexpected times.

Say you've set your System Preferences to auto-hide the dock, and further that the dock shows up at the bottom of the screen.  Now say a window on screen 1 has focus and you expose the dock.  So far so good.  Now give focus to a window on another screen and expose the dock on *that* screen by moving the cursor to the bottom of the other screen.  The dock will unhide on that other screen *and* Hammerspoon will trigger a layout change.  This means that when you unhide the dock on a new screen all your windows move around!  That's not so good.  ;)

I'm not sure why you'd get a layout change in that case since clearly the screen layouts aren't changing, only the dock is getting exposed on different screens.  I definitely want to avoid moving my windows around in that case.

**Comment by cmsj** [comment]
So the way the screen watcher works is to just register with macOS for the NSApplicationDidChangeScreenParametersNotification event, which does actually get triggered when the Dock moves, because that changes the area of the screen on which apps should be drawing.
I think it probably shouldn't trigger when the dock is set to autohide, because then apps aren't supposed to be actively avoiding it, but for whatever reason, Apple either wants that notification, or hasn't noticed that it's happening.

The only workaround I can think of would be to fetch the fullFrame() for each hs.screen object, cache them and then in your layout_change() callback, check to see if the same number of screens are in the same order with the same sizes :/

(also fwiw, you filed this issue on our website repo, rather than the main github.com/Hammerspoon/hammerspoon repo :)
